server:
  port: 8080
  servlet:
    context-path: /SbLayuiDemo
spring:
  thymeleaf:
    prefix: /console/
    suffix: .html
    cache: false
  devtools:
    restart:
      enabled: true
      exclude: /console
  datasource:
    username: lixinrong
    password: lixinrong
    url: jdbc:mariadb://127.0.0.1:3306/base_pro?Unicode=true&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml